wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.7
    cli_version: 0.16.4
    framework: sklearn
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1711050668.0
    t:
      1:
      - 5
      - 53
      - 55
      2:
      - 5
      - 53
      - 55
      3:
      - 2
      - 14
      - 23
      - 24
      4: 3.11.7
      5: 0.16.4
      8:
      - 5
      - 13
      13: linux-x86_64
n_std:
  desc: null
  value: 1.0e-08
burnin:
  desc: null
  value: 50
noise_svar:
  desc: null
  value: 1.0e-08
scalar:
  desc: null
  value: 1
